site_name: SDSDG-Lib
repo_url: https://github.com/Bruno-Gomes-QA/sdsdg-lib
repo_name: Bruno-Gomes-QA/sdsdg-lib
edit_uri: tree/master/docs

theme:
  name: material

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [sdsdg_lib]