site_name: SDSDG-Lib
repo_url: https://github.com/Bruno-Gomes-QA/SDSDG
repo_name: Bruno-Gomes-QA/SDSDG-Lib
edit_uri: tree/main/api/docs

theme:
  name: material

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [api]